//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duanlamchung
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagerEntities : DbContext
    {
        public HotelManagerEntities()
            : base("name=HotelManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<room_types> room_types { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<service_orders> service_orders { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
