//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duanlamchung
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public decimal total_room_price { get; set; }
        public decimal total_service_price { get; set; }
        public decimal grand_total { get; set; }
        public string payment_status { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
