//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duanlamchung
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_orders
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public int service_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime order_time { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual service service { get; set; }
    }
}
